--- 
clone: 
  depth: 1
kind: pipeline
name: silont-project
steps: 
  - 
    commands:
      - apt update -qqy && apt install -qqy openjdk-11-jre-headless
      - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh
      - chmod +x compile.sh
      - bash compile.sh -c silont
    environment: 
      TOKEN: 
        from_secret: BOT_API_KEY
    image: fadlyas/kernel_dockerfile:latest
    name: azrim
    trigger: 
      branch: 
        - new
        
